### ISSUE TITLE
Getting error when looking up 5 letters domain

### ISSUE THREAD

**Issue by Rocks333** [stx-labs/stacks.js#101]
I get this

> ~$ blockstack lookup porno.id
> {
>     "error": "Unexpected error, 'unicode' object has no attribute 'has_key'",
>     "help": "Try getting latest version of CLI with \"sudo pip install blockstack --upgrade\""
> }

same happens for other similar domains, I suppose there is a ban list or something?

Not really it the spirit of free decentralized systems?

**Comment by Rocks333** [comment]
Same happens for number of other words

**Comment by jcnelson** [comment]
Hey Rocks333, thanks for letting me know!  I'm taking a look; we're about to make a new release that fixes a bunch of bugs here.

**Comment by Rocks333** [comment]
Great to know! When we can expect it?

**Comment by jcnelson** [comment]
Since the name `porno.id` does not have valid zonefile data associated with it, the `lookup` command will fail (since the client will be unable to fetch the associated profile data).  However, when I run `blockstack get_name_zonefile porno.id`, I get this:

```
{
    "zonefile": "\"BM-2cX3wX3UKXFtG3w1DNjedNaXymHcdp8KuF\""
}
```

This is the off-chain data whose hash matches the on-chain hash for `porno.id`.  If this is a name you own, you should use the `blockstack migrate` command to give `porno.id` a default zonefile and profile.

I'm going to go ahead and close this issue, since the latest stable release correctly fetches this name's zone file data.
