### ISSUE TITLE
`lookupProfile` throwing error with `.btc` usernames

### ISSUE THREAD

**Issue by pradel** [stx-labs/stacks.js#1105]
**Describe the bug**

Calling lookupProfile is throwing the following error when trying to access `.btc` usernames.

```
[ERROR] resolveZoneFileToProfile: error fetching token file https://gaia.blockstack.org/hub/1KvMJEjCMjwLxK4VHJn3wyYCcEuzB8qjZH/profile.json: Error: Token issuer public key does not match the verifying value
```

**What version of Blockstack.js are you using?**

- @stacks/auth - v2.0.1

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**

`@stacks/auth`

**To Reproduce**

```
import { lookupProfile } from '@stacks/auth';

await lookupProfile({ username: 'leopradel.btc' });
```

**Expected behavior**

The profile should be returned, it's working fine for `*.id.blockstack` and `*.id.stx` usernames.

**Additional context**

I already faced the same error for `*.id.stx` usernames before in https://github.com/blockstack/stacks.js/issues/1016 and submitted a pull request to fix it.
For this one, I tried to debug but didn't manage to make it work.

**Comment by ahsan-javaid** [comment]
When we call `lookupProfile`, internally the verifyProfileToken function is called
https://github.com/blockstack/stacks.js/blob/1af7a18b1017981f5b44c1006d940eb4648d0491/packages/profile/src/profileTokens.ts#L105-L114

`publicKeyOrAddress` is the STX address returned by the API 
```
curl https://stacks-node-api.mainnet.stacks.co/v1/names/leopradel.btc
```
Response:

```
{
  "address": "SP3VCX5NFQ8VCHFS9M6N40ZJNVTRT4HZ62WFH5C4Q",
  "blockchain": "stacks",
  "expire_block": 0,
  "last_txid": "0x60e3e5faf0d8f79054b3acf7545939f099fe466a4e78a4d23bea70bc25b1e2a3",
  "status": "name-register",
  "zonefile": "$ORIGIN leopradel.btc.\n$TTL 3600\n_http._tcp\tIN\tURI\t10\t1\t\"https://gaia.blockstack.org/hub/1KvMJEjCMjwLxK4VHJn3wyYCcEuzB8qjZH/profile.json\"\n\n",
  "zonefile_hash": "7dff651a82090bbbc37260917ae9621e5c75bda5"
}
```
and we compare it with the address that we got from the public key which is: 
https://github.com/blockstack/stacks.js/blob/1af7a18b1017981f5b44c1006d940eb4648d0491/packages/profile/src/profileTokens.ts#L106

So the addresses:
`publicKeyOrAddress: SP3VCX5NFQ8VCHFS9M6N40ZJNVTRT4HZ62WFH5C4Q`
`address: SP37RJG6SG88F2R1GMCSA2G1XMPWM9JFEAYJ2V20G`

are not equal that's why `verifyProfileToken` throws `Token issuer public key does not match the verifying value` at
https://github.com/blockstack/stacks.js/blob/1af7a18b1017981f5b44c1006d940eb4648d0491/packages/profile/src/profileTokens.ts#L113

cc: @zone117x @reedrosenbluth 
Because the addresses do not match what are your thoughts in terms of if its a stacks.js issue or server side issue. Any ideas in terms of why the same addresses are not returned by server side.

**Comment by zone117x** [comment]
I'm not seeing any tx related to `SP37RJG6SG88F2R1GMCSA2G1XMPWM9JFEAYJ2V20G`. Maybe a bug with whatever is registering `.btc` names? I'm not familiar with that code.

**Comment by zone117x** [comment]
@MarvinJanssen any ideas?
cc @asimm241 as well

**Comment by friedger** [comment]
I would think that the issue is more on the extension that creates the token and this issue is somehow related to derivation paths and this https://github.com/blockstack/stacks-wallet-web/issues/1412

The b58 address `1KvMJEjCMjwLxK4VHJn3wyYCcEuzB8qjZH` of the profile url is `SP37RJG6SG88F2R1GMCSA2G1XMPWM9JFEAYJ2V20G`, however the owner of the profile is `SP3VCX5NFQ8VCHFS9M6N40ZJNVTRT4HZ62WFH5C4Q`

**Comment by asimm241** [comment]
I tried to debug this issue, I can not say conclusively, but I also think  the problem resides somewhere in web-wallet.

**Comment by markmhendrickson** [comment]
I'll investigate this with the UserX team and follow up 👍

**Comment by friedger** [comment]
Oh, iceboxed 😱

**Comment by markmhendrickson** [comment]
This is in the Splat icebox, but the UserX backlog. We'll get to it soon. 🙏

**Comment by friedger** [comment]
The problem is that the profile token is signed with the `dataPrivateKey` of the account, while the `stxPrivateKey` is used to create the stx address that is sent to the client from the name endpoint and that owns the `.btc` name. 

Therefore, the client won't be able to verify the profile token.

**Comment by friedger** [comment]
Solution? All users with a name have to resign their profile token?

**Comment by pradel** [comment]
In order to provide an incremental migration path and allow Sigle to use the Hiro wallet extension:
1. https://github.com/blockstack/stacks.js/pull/1117 this pr needs to be updated, and the fix of @friedger should be applied **only** if no names are attached to the `dataPrivateKey`. The result would mean that `.btc` domains are working and old `.id.stx` names keep working.
2. Second step, if a name is attached to the `dataPrivateKey`, the user should be prompted to migrate the name to the new `stxPrivateKey` that Hiro wallet is using. As this requires an on-chain transaction, the best would be to have it sponsored so users don't pay the tx fees.

@markmhx @kyranjamie

**Comment by markmhendrickson** [comment]
@pradel Thanks for the action items summary 🙏 

To be clear here, for Sigle to migrate to the Hiro Wallet extension, only your step #1 needs to be implemented as part of this PR. Whereas step #2 can be tackled subsequently in a separate PR, as it's not strictly needed for Sigle migration. Correct?
