### ISSUE TITLE
Failed to broadcast update transaction

### ISSUE THREAD

**Issue by shivamsatija** [stx-labs/stacks.js#115]
**blockstack update** 22d9c27264545b90a22b10c25941.id '{"$origin": "22d9c27264545b90a22b10c25941.id","$ttl": "3600", "uri": [{"name" :"_new_info", "priority":"10", "weight":"1", "target": "https://www.facebook.com/shivam.satija.7"}]}'
Enter wallet password: 
[2016-07-25 03:38:55,058] [DEBUG] [session:127](10647) [10647] Connect to bitcoind at http://blockstack@bitcoin.blockstack.com:8332, timeout=300.0
**Failed to broadcast update transaction**

My
**blockstack info**
{
    "advanced_mode": false, 
    "cli_version": "0.0.13.7", 
    "consensus_hash": "c95f0b9ed4e776cfd808840328790754", 
    "last_block_processed": 422196, 
    "last_block_seen": 422202, 
    "server_alive": true, 
    "server_host": "node.blockstack.org", 
    "server_port": "6264", 
    "server_version": "0.0.13.0"
}

**Please tell me how should i update this data through CLI**

**Comment by jcnelson** [comment]
Hi @shivamsatija, apologies for the delay (was traveling).

You were doing everything correctly.  I just queried your name's zonefile information, and got this:

```
$ blockstack get_name_zonefile 22d9c27264545b90a22b10c25941.id
{
    "$origin": "22d9c27264545b90a22b10c25941.id", 
    "$ttl": 3600, 
    "uri": [
        {
            "name": "_new_info", 
            "priority": 10, 
            "target": "https://www.facebook.com", 
            "weight": 1
        }
    ]
}
```

It looks like the transaction went through in the end.  Did you get it to work simply by re-trying?  I ask because the only ways your command might have failed would have been because (1) you were having network connectivity issues, (2) your payment address had unconfirmed transactions, or (3) you didn't have enough UTXOs to cover the mining fee (which is dynamically selected with bitcoind's `estimatefee` RPC call).
