### ISSUE TITLE
Remove nodejs `buffer` polyfill

### ISSUE THREAD

**Issue by zone117x** [stx-labs/stacks.js#1256]
Stacks.js uses the nodejs `buffer` module for representing binary data in most areas. This is mostly a legacy artifact from years ago. Since then, generally all js environments support [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) which accomplishes most of what `buffer` is used for. 

In fact, the [`buffer`](https://www.npmjs.com/package/buffer) polyfill for web browsers inherits from a [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) instance and adds some functionality. Unfortunately, that polyfill adds much more than we need, and results in bundle bloat. 

Generally, all the code in stacks.js only uses a few buffer-specific encoding features like to/from `hex`, `base64`, and `utf8`. From firsthand experience, I can say this is a relatively trivial refactor (see [micro-stacks](https://github.com/fungible-systems/micro-stacks) for inspiration).

**Comment by janniks** [comment]
Thanks for bringing this up — definitely on the roadmap!

---

~Since it's a bit ~tricky~ annoying to coordinate the packages and dependencies, I propose this order:~
~1. https://github.com/hirosystems/stacks.js/issues/1257~
~2. https://github.com/hirosystems/stacks.js/issues/1258~
~3. _coming soon_~
