### ISSUE TITLE
renew fails with "Failed to estimate fee" if wallet has less than 12.3456789 BTC

### ISSUE THREAD

**Issue by stiell** [stx-labs/stacks.js#134]
`blockstack renew` fails with "Failed to estimate fee". With `BLOCKSTACK_DEBUG=1`, it shows e.g.:

> Not enough inputs for transaction (total: 300000, to spend: 1234567890, fee: 32000)

It seems that the fee estimation needs to have more than 12.3456789 BTC in the wallet in order to function.

For this error to go away, I need to change `renewal_fee=1234567890` in https://github.com/blockstack/blockstack-cli/blob/498c30857b9ab754919a45fcd52c19bc49eb2dad/blockstack_client/backend/nameops.py#L141 to a lower value.

**Comment by jcnelson** [comment]
Ah, I see what's happening.  The mechanism that estimates the transaction fee needs to have a name fee, so it can calculate a mock renewal transaction of equivalent byte length to the actual renewal transaction.  But since the fee estimation must take into account the number of UTXOs that will be consumed, it tries to see if you actually have at least 12.3456789 BTC-worth of outputs.  I'll have it use the actual renewal fee instead.

**Comment by jcnelson** [comment]
This has been fixed in 0.14.0, now merged to master.  Please re-open if the problem continues.
