### ISSUE TITLE
"Failed to broadcast update transaction﻿⁠⁠⁠⁠" on profile update

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#179]
Hey,

I tried to update my profile with `blockstack update vsund.id blockstack/zonefile﻿⁠⁠⁠⁠` and I got a ` ﻿⁠⁠⁠⁠Failed to broadcast update transaction﻿⁠⁠⁠⁠` error.

I use "Blockstack cli version 0.14.0.7" (set up with pip) on Archlinux.

- [content of `blockstack/zonefile`](https://github.com/blockstack/blockstack-cli/files/628979/zonefile.txt)
- [full error log](https://github.com/blockstack/blockstack-cli/files/628980/output.txt)

Thanks for any help in advance :)

**Comment by jcnelson** [comment]
Hey, thanks for the trace and zonefile!  Will take a look and get back to you soon :)

**Comment by jcnelson** [comment]
Hi @vsund, I spent some time digging through the various ways this could have happened.  Your log was really helpful.  The interesting line is this one:

```
[2016-12-03 17:05:45,841] [ERROR] [nameops:285] (4011.139811712086912) Unable to create transaction
```

This gets triggered in `blockstack_client/backend/nameops.py` due to a caught assertion error.  Unfortunately, it doesn't print out the stack trace here when `BLOCKSTACK_DEBUG` is set, but there are several possible assertions that could have failed.

I just pushed version 0.14.0.8 to `master`.  The only difference between 0.14.0.7 and 0.14.0.8 is that it will print the stack trace when this kind of assertion failure happens.  You can grab it with:

```
$ pip install git+git://github.com/blockstack/blockstack-cli.git
```

If the `update` problem happens again, please let me know what happens when you try while setting `BLOCKSTACK_DEBUG=1`.  Thank you again for your patience and for sending me the log and zonefile :)

**Comment by vsund** [comment]
After installing blockstack in a virtualenv (with Jude's assistance) there's [this output](https://github.com/blockstack/blockstack-cli/files/650378/output.txt).

**Comment by jcnelson** [comment]
Thanks for the output!  I think I fixed the problem you were seeing as of b3d694ecf672e23e0013aff9eabbbb67c237ea31.  As always, you can get the latest with `pip install git+git://github.com/blockstack/blockstack-cli.git` (recommend using a new virtualenv).

**Comment by vsund** [comment]
I think one error is gone, but (now?) there's another one :)
See [here](https://github.com/blockstack/blockstack-cli/files/652179/output.txt)

**Comment by jcnelson** [comment]
Hi @vsund, thanks for giving me a log!

I noticed this in your output:

```
[2016-12-14 16:56:08,241] [DEBUG] [rpc:843] (24380.140046932382592) RPC endpoint already running (/home/me/.blockstack)
```

You may have used an older version of the daemon that was still running.  Can you try the following?

```
$ blockstack rpcctl stop
```

to stop the daemon, and then try the update again?  You will be re-prompted for your password.  You can verify that the daemon is running by checking the PID file at `/home/me/.blockstack/api_endpoint.pid`.

**Comment by vsund** [comment]
Great! Went through without errors and is now queued :)
