### ISSUE TITLE
Missing redirect in authBrowser.js

### ISSUE THREAD

**Issue by lacabra** [stx-labs/stacks.js#199]
L30 is missing a blockstack.org redirect (there used to be a timeout instead of the protocol check), but now if auth is not handled by protocol (even when there is a protocol handler), there is no link to the anonymous login

**Comment by shea256** [comment]
Thank you @lacabra, I'm on it! Will ping you when this has been fixed.

**Comment by shea256** [comment]
@lacabra I realized that there isn't actually a problem here with that line.

As you can see, there's an actual redirect when the protocol handler is not detected: https://github.com/blockstack/blockstack.js/blob/master/src/auth/authBrowser.js#L28

If you are not getting redirected, it is likely due to one of the following:

(a) the protocol handler was improperly detected when it doesn't exist
(b) the redirect failed
(c) the script did not load at all

Can you please try again and let me know if there's any output in your console?

**Comment by lacabra** [comment]
@shea256 I agree with you that the logic is valid as it is right now.
I originally reported this issue because of the Hello Blockstack tutorial on YouTube, in which an automatic redirect happens in the background around 11:55, which doesn't happen in the current code. I was trying the code on a MacOS/Chrome, and the current blockstack-browser (0.6.2) doesn't allow to register a profile as reported in [#388](https://github.com/blockstack/blockstack-portal/issues/388) and [#389](https://github.com/blockstack/blockstack-portal/issues/389), effectively leaving me unable to test the hello blockstack app.

In my case, the protocol handler is detected properly, but
- if I proceed with the protocol handler, I end up with a blockstack browser that cannot authenticate me
- if I choose the protocol handler *not* to handle the request, I end up with nothing

So I effectively have no way to test the HelloBlock app currently.

**Comment by larrysalibra** [comment]
@lacabra You should be able to register a profile now on the browser.

Please re-open this issue if you're still having problems with the redirect.
