### ISSUE TITLE
Use local API server in test mode

### ISSUE THREAD

**Issue by scott-martin** [stx-labs/stacks.js#221]
The method `doPublicKeysMatchUsername` in authVerification.js line 43 has 'https://core.blockstack.org/v1/names/' hardcoded as the url to look up names. When developing using a local regtest network, this won't work.

Need to add the ability to make that URL configurable.

**Comment by jcnelson** [comment]
As far as I can tell in the call graph for the Browser and other packages, all paths to `doPublicKeysMatchUsername` pass in a value for `nameLookupURL`.  I'm thinking this should be a required argument, since ultimately users will be choosing which Core nodes to use (either local ones or ones running on servers they trust).

**Comment by larrysalibra** [comment]
This is fixed in the current release version (0.9.1)

Thanks again for reporting it @scott-martin
