### ISSUE TITLE
Improve wording on the use of "tokens"

### ISSUE THREAD

**Issue by vsund** [stx-labs/stacks.js#239]
I was trying to fetch profiles through `extractProfile()` and it requires a token. I was confused which token it wants to get and what a token actually is in that case.
Turns out that it's a [JSON web token](https://jwt.io) in that case and carries all the relevant (and signed) profile details.

We should try to use less appearances of the word "token" (especially given the L2 token now :D) and make more clear what a specific token is referring to.

cc @larrysalibra

**Comment by vsund** [comment]
We probably can get rid of the word "token" here completely. What about calling it simply "encoded profile" (and then document somewhere that it's a JSON web token)?

**Comment by cryptoquick** [comment]
I understand the confusion between cryptocurrency "tokens", but calling it a token is fine in the context of web application development. token-based auth is a very common pattern. that said, calling it a JWT, to be more specific, is probably fine, but not all that necessary, imo.

**Comment by jackzampolin** [comment]
@cryptoquick 👋

**Comment by larrysalibra** [comment]
Thanks for this feedback. In general we should error on the side of verbosity and avoid acronyms whenever possible so that it is very clear to developers what we are talking about.

I think we've been pretty consistent in our documentation language about calling them "authentication request tokens" and "authentication response tokens" - if you find a place in our docs or comments where that's not the case, please open an issue or pull request to fix it. For now I'm going to close out this issue.
