### ISSUE TITLE
Profile fetching from URL fails with HTTP 404

### ISSUE THREAD

**Issue by raulk** [stx-labs/stacks.js#307]
At the [Democracy Earth Foundation](http://democracy.earth), we are integrating Sovereign with with Blockstack Login. We are building an accounts-blockstack module for Meteor, which we hope to open source soon. Unfortunately we're being blocked by this issue.

Commit 8ed0cef3402637d1a8fe78c15fee67abdbbbd10f elided the profile JSON from the auth response, which now includes a URL where the profile can be found instead.

Unfortunately, under a normal `redirectToSignIn()` request, followed by a `handlePendingSignIn()` call, fetching the profile results in an HTTP 404, therefore the application cannot access the user's info any longer.

*Versions:*
* blockstack.js 0.13.7 (latest version on NPM at the time this issue is opened).
* Blockstack browser: latest (just updated -- where can I find the version number).

The Hello Blockstack example app has not been updated to use the latest blockstack.js version, hence it continues working as it doesn't send the `do_not_include_profile: true` flag during the auth flow.

**Comment by raulk** [comment]
Downgrading to v0.13.0 (latest version without the referenced commit) works.

**Comment by kantai** [comment]
Hey @raulk -- thanks for raising this issue --

The profile URL should only 404 if the profile hasn't actually been written yet -- do you have examples of URLs that return this 404?

Ideally, an application that wanted to use data from a user's profile that 404s would display a prompt to the user to go back and finish creating their profile.

Or is the issue here that the 404 causes an exception in the `handlePendingSignIn` and you can't finish processing the signin?

**Comment by raulk** [comment]
@kantai https://gaia.blockstack.org/hub/1KVBj2Hkycwe5Xk656R6EbjM5k6AkHXufE/0/profile.json

> Or is the issue here that the 404 causes an exception in the handlePendingSignIn and you can't finish processing the signin?

Exactly.

**Comment by kantai** [comment]
Okay -- @yknl suggested an alternative interface, where in cases like this, `handlePendingSignIn` will continue the sign-in process, but instead of `resolve(userData)`, it will call `reject(userData)`. What are people's thoughts on this?

**Comment by jcnelson** [comment]
How hard would it be to permit authentication without a profile?  Asking because I can see ways that a user can accidentally lose their profile, but not their name and zone file (examples: user deletes their storage provider account, the state the user is in censors the storage provider, the service provider crashes, the user has a very big profile or a maliciously-crafted profile that shouldn't be loaded anyway).

**Comment by larrysalibra** [comment]
Is this still an issue? @kantai @raulk

**Comment by yknl** [comment]
Closing this issue for now, please re-open if it still exists.
