### ISSUE TITLE
blockstack.js won't work with npm git links

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#318]
Currently, we can't support an npm dependency on `blockstack.js` using a git link like:

```
"blockstack": "git://github.com/blockstack/blockstack.js#develop"
```

This can be pretty annoying for testing out changes in `blockstack.js` on different apps.

I _think_ this happens because we need to build the `/lib/` directories for it to be used from a node app -- should probably be solvable with a `prepublish` definition.

**Comment by larrysalibra** [comment]
This would be nice to have. Marking it as help wanted in case a community member can help us with this.

**Comment by vsund** [comment]
The [current `package.json`](https://github.com/blockstack/blockstack.js/blob/9a0b0b32100ae81946c805b4ab02f9c0c8e512c6/package.json#L11) seems to have a `prepublish` directive in place that *should* already do this.

The issue seems to be that NPM doesn't run `prepublish` on git installs and one should use `prepare` for this.
I played a little bit around with this at https://github.com/vsund/blockstack.js/tree/feature/auto-build-on-install and it also has some weird behaviour: After a `npm add git://github.com/vsund/blockstack.js#feature/auto-build-on-install` I have a `lib/` folder but no `src/` folder 🤔

**Comment by larrysalibra** [comment]
We have a `prepare` now - please re-open if this is still an issue.
