### ISSUE TITLE
NPM install leaves a dirty git history

### ISSUE THREAD

**Issue by jackzampolin** [stx-labs/stacks.js#368]
When I run `npm i` on my local machine it leaves a dirty git history. The following files are changed:

```
$ git status
On branch feature/blockstack-operations
Your branch is up-to-date with 'origin/feature/blockstack-operations'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   dist/blockstack.js
	modified:   docs.json
	modified:   docs/index.html

no changes added to commit (use "git add" and/or "git commit -a")
```

The proposal here would be to add the following to the `.gitignore` file:

```
dist/
docs.json
docs/index.html
```

cc @cwackerfuss @yknl @larrysalibra

**Comment by larrysalibra** [comment]
@jackzampolin those need to be committed to the repo so can't be in gitignore. 

dist/blockstack.js is where someone who just uses plain javascript can grab a copy without needing a node/npm toolchain.

The docs are where the docs are served from.

We can probably modify the script hooks so that npm install doesn't run npm run build during install.

**Comment by 0x-r4bbit** [comment]
This landed as https://github.com/blockstack/blockstack.js/pull/416/commits/a19e651f2572b0c35b15c6b88012532ef50abad3 and can be closed no?
