### ISSUE TITLE
Conduct research for Blockstack iOS software developer kit

### ISSUE THREAD

**Issue by larrysalibra** [stx-labs/stacks.js#371]

**Comment by yknl** [comment]
Sharing my research findings on the best way forward for the mobile SDKs.

1. Native wrapper for `blockstack.js` on iOS and Android 
On iOS, this requires the use of `JavascriptCore`, which exposes a Javascript engine to run JS code. But it does not provide a real browser environment. i.e. No access to `window`, `localStorage` or network requests. Given the way we've written blockstack.js, it would take far too much effort to get it working on `JavascriptCore`. Even if we were able to get this working, it would have some performance impact and be a pain to debug/maintain. In Android this requires shipping a Javascript engine with the library. After some attempts to get this to work on iOS, my opinion is that we're not saving ourselves time and would be incurring significant technical debt with this approach. [Reference Blog Entry](https://www.skyscanner.net/blogs/developing-mobile-cross-platform-library-part-3-javascript)

2. Cross-platform core logic using C++ and native UI
We could write the core logic in C++ and then use native UI components in iOS and Android. You can interface with C++ code using JNI (Java Native Interface) in Android and Objective-C++ in iOS. This approach has a major advantage in that we can potentially compile the core logic code for other platforms like macOS and Windows for maximum code reuse. The downside here is that it's C++. Successful projects that use this approach to achieve cross-platform codebase sharing include [Dropbox](https://oleb.net/blog/2014/05/how-dropbox-uses-cplusplus-cross-platform-development/) and [Slack](https://slack.engineering/libslack-the-c-library-at-the-foundation-of-our-client-application-architecture-97470b5ef9b3).

3. Separate native SDKs on iOS and Android
In my opinion, this is the most sane option out of the three. We don't need to worry about platform compatibility bugs and can take full advantage of optimizations on each platform. We can take a phased approach to building this out as well. Since we're not building a native mobile Blockstack Browser yet, we can defer implementation of most of `profiles` functionality in `blockstack.js`. The MVP could be just implementing `auth` and `storage`. This approach may not even necessarily increase initial development time as both Android and iOS can happen in parallel and independently. Additionally, the iOS SDK written in Swift could with some modifications be used on macOS as well. When in the future, the code base has grown to a certain point and when we have more engineering resources, we can consider sharing the core code using C++ as in approach 2.

Recommendation: 
**Separate native SDKs on iOS and Android** seems to be the best approach. 

@larrysalibra @kantai @shea256 @muneeb-ali 
Let me know what you guys think and feel free to suggest alternate approaches.

**Comment by larrysalibra** [comment]
Tagging the related Android issue here so that we can have a discussion in one place: https://github.com/blockstack/blockstack.js/issues/372

**Comment by friedger** [comment]
What about sharing code using Kotlin native (https://kotlinlang.org/docs/reference/native-overview.html) ?

**Comment by yknl** [comment]
The Blockstack iOS SDK: https://github.com/blockstack/blockstack-ios
