### ISSUE TITLE
Mark deleteFile as NotImplemented in the documentation

### ISSUE THREAD

**Issue by kantai** [stx-labs/stacks.js#378]
deleteFile isn't currently implemented, so we should indicate as such in the documentation

**Comment by vilsbole** [comment]
Indeed it is confusing since the [PR](https://github.com/blockstack/blockstack.js/pull/290) is marked as merged but both the implementation in both `master` and `develop` simply throws an `[Error]`(https://github.com/blockstack/blockstack.js/blob/286df82401c5be8d89e352054e2192e0f600ea98/src/storage/index.js#L163-L165)

**Comment by kantai** [comment]
Documentation is fixed.
