### ISSUE TITLE
[feature-request]: Mechanism to get user's public key.

### ISSUE THREAD

**Issue by fiatexodus** [stx-labs/stacks.js#535]
Public keys are derived implicitly in the encryptContent method of Blockstack.js as of May 28, 2018, and can be over-ridden with another user's public key if you wish to encrypt for that user.

To date, Stealthy and possibly other dApps have been using the getPublicKeyFromPrivate to get the public key for a particular user and expose it for the purpose described above. After talking with @larrysalibra, he mentioned this method is not part of the public API in Blockstack.js and to file this feature-request.

**Comment by hstove** [comment]
I am looking to do this with Kanstack as well. I've done a lot of digging into the code, and I'm not sure that there is a way to do this in blockstack.js, given the way Blockstack currently works.

The crux of the issue is that the way we create a user's Gaia address goes through a `sha256` call. blockstack-browser uses the [`ecPairToAddress` utility function](https://github.com/blockstack/blockstack.js/blob/master/src/utils.js#L103) to generate a Gaia address from a public key. Here's the code:

~~~javascript
return address.toBase58Check(crypto.hash160(keyPair.publicKey), keyPair.network.pubKeyHash)
~~~

Because the public key goes through a `sha256` first, it seems to me that there is no way to go backwards and get a public key from a Gaia address.

IMO, this is kind of a tough flaw of our system, as making this easy for developers would be great. There shouldn't be security risks of publishing a user's public key, especially when they go through the `publish_data` authentication flow.

I see that when we use `putFile` with the option `sign: true`, we create a signature object, which includes the public key. This allows us to verify another user's signature.

As an app developer, I guess a solution would be to store the user's public key in some way that is accessible to other users. A simple way would be to call `putFile('public_key.txt', appPublicKey)`. You could only do this for users that sign into your app. Then, you can use that stored public key to encrypt their content later.

**Comment by fiatexodus** [comment]
I basically modify all the Blockstack SDK/API releases to expose get public key from private in my own forks for Stealthy products.

BTW, Stealthy does exactly what you're saying about exposing the public key--/<user's gaia bucket for stealthy>/pk.txt.  Our protocol is effectively designed to allow other apps to allow app and user data sharing across cryptographic boundaries using this mechanism. That API will be coming out in the next quarter if our current plans hold. Pretty sure other devs did that too (in similar ways) for their apps. I believe @jcnelson may have ideas/proposals for doing this through another mechanism on the forum or elsewhere.

**Comment by larrysalibra** [comment]
@AC-FTW @hstove We have a mechanism for this on the roadmap. See this issue for details: https://github.com/blockstack/blockstack.js/issues/458

**Comment by yknl** [comment]
Closing and tracking issue in https://github.com/blockstack/blockstack.js/issues/458
