### ISSUE TITLE
Expose the wallet APIs

### ISSUE THREAD

**Issue by moxiegirl** [stx-labs/stacks.js#543]
Spoke with @kantai  these are documented but not exposed.  For example, https://github.com/blockstack/blockstack.js/blob/master/src/operations/txbuild.js#L1100

We will need to add these back in.  Aaron also said, some of the old wallet functions like “get my spend address” are just done in JavaScript by a given client, and don’t have explicit APIs in blockstack.js so maybe @larrysalibra you can speak to that a bit more.

These are the categories of the APIs that the core spec said should be in javascript:

_Blockstack clients should use [blockstack.js](https://github.com/blockstack/blockstack.js)_

* for querying client-side configuration state.
* client-side configuration management.
* query the status of pending transactions.
* wallet management
* query balances.
* manage keys and query UTXOs.
* generate transactions, and send transactions.
* to encrypt keys
* manage keys in a client wallet.
* register and manage names.
* generating transactions.
* broadcast transactions.

**Comment by larrysalibra** [comment]
This interface is marked as private because there is no way for a blockstack app to use it since the authentication flow doesn’t support providing access to user wallets.

We rcan emove the private notation but I think this will confuse app developers who will think that they can do blockstack transactions in their apps only to find that this isn’t really possible in the way that this API implies.

If we’re going to make the API public we should make it more consistent in line with the discussion in the pull request that added this functionality https://github.com/blockstack/blockstack.js/pull/433
