### ISSUE TITLE
Ability to withdraw bitcoins from the Blockstack wallet

### ISSUE THREAD

**Issue by rikur** [stx-labs/stacks.js#58]
I would like to withdraw some Bitcoins form my Blockstack wallet:
`blockstack withdraw address amount`

Alternatively, documentation could be written on how to decrypt the private key so that I can import the wallet to another bitcoin client and send out the Bitcoins that way.

**Comment by muneeb-ali** [comment]
I was helping @JFiscella debug an issue and we noticed that the ability to withdraw funds should be there not just for the payment address but also for the owner address (in case you accidentally sent BTC to the owner address, which is what happened in this case).

**Comment by sfmcnally** [comment]
I would also like to be able to withdraw excess bitcoin or have some instructions for how to decrypt the private key.

**Comment by koppenhoefer** [comment]
I see that I am not the only one who can get confused over this :) Blame it on the coffee...

I just did "blockstack deposit" and got a heading text that says "Wallet created" (yeah). Did it create a wallet?.. or did it create a deposit?.. Or did it create a wallet that I will use to make a deposit into an "account" (see later). Then I see a text talking about a **_MASTER_PRIVATE_KEY_** (I assume this is the private key of my newly created wallet),.. and something else called an **_ADDRESS_**. The 'address' has a message after it which is "Send bitcoins to the address specified". So I guess that that address is not the address of MY wallet. After all,.. when I purchase something don't I want to send money to anywherebutmyownwallet? So it must be a bitcoin address of someone else's wallet? So what's the address of my own wallet where I can send some bitcoins in order to then send those bitcoins to the ADDRESS? Call me confused... :(

Of course, when I do "blockstack names" I see an entirely different address with a different value as that which popped out when I did "blockstack deposit". Hmmm. Maybe "that's" my own wallet address?

I wonder which address' is the address of my newly created wallet,.. and which 'address' is the address of someone else's wallet to which bitcoins will be sunk (and I assume burned) when sourced from my wallet. Does anyone know? I don't want to send too many bitcoins to the wrong ADDRESS,.. and end up in the same situation as @rikur and @sfmcnally .
On https://blockstack.org/docs/basic-usage I read "_you'll need to deposit bitcoins in your **ACCOUNT**_". Hmm. What's that? Is this an account that Blockstack manages?... or did this text intend to say "deposit bitcoins in your _wallet_"... or did this text intend to say "send bitcoins to that _ADDRESS_". :(

When I do "blockstack balance" I see ADDRESS again... with a balance of 0.0. Can I understand that "a balance of 0.0" is the same thing as "a deposited amount of 0.0"? Is this showing me the amount in my "wallet"?.. or is this showing me the amount that I've deposited (somehow) in my "account"?

It'd be really cool if I could manage my new blockstack wallet,.. say, in AirBitz?

I notice that doing "blockstack register blahblah.id" requests the wallet password and then talks about cost. So I guess that the phrase "deposit bitcoins in your account" was meant to say "load up bitcoins into the wallet address"; But I'm not totally sure on this one.

**Comment by Gitju** [comment]
@koppenhoefer `blockstack deposit` shows you an address where to send Bitcoin to pay the costs for a registration.

A `blockstack balance` shows the balance of what you have send to `blockstack deposit`.

You can get the costs for a registration with `blockstack price <johndoe>.id`

A `blockstack register <johndoe>.id` uses then the Bitcoin that you have send.

**Comment by jcnelson** [comment]
There's a way to do this, but it's currently a manual process.  First, you'll have to install a Bitcoin wallet.  Next, you'll need to get your private keys out with `blockstack wallet`.  Then, you can import your private keys into your Bitcoin wallet, and use them to transfer your funds.

A Blockstack CLI command to transfer funds from either the owner or payment keys will be added in 0.14.1.

**Comment by jcnelson** [comment]
This is now added with the `withdraw` command.

**Comment by jpuck** [comment]
@jcnelson is there any documentation for the `withdraw` command? Only the recipient address is marked as required, but all attempts to use this command result in:

> Invalid arguments.  Please try again.

Can the recipient address be any wallet, such as a Coinbase wallet?

**EDIT** figured it out - there's an issue with the interactive prompt. Passing the arguments directly to the command works fine, but when inputting the same arguments to the prompt results in the error.

See also: https://forum.blockstack.org/t/blockstack-withdraw-always-results-in-invalid-arguments-please-try-again/3451/2

**Comment by Anastik** [comment]
@jpuck thanks for posting this. I couldn't figure out why I couldn't withdraw my funds until I read your comment. I appreciate it!
