### ISSUE TITLE
Replace elliptic with bitcoin-ts

### ISSUE THREAD

**Issue by friedger** [stx-labs/stacks.js#585]
Operations of elliptic can be replace with bitcoin-ts in webassembly with 10x better performance:
https://blog.bitjson.com/just-released-webassembly-version-of-secp256k1-10x-faster-than-javascript-eb3cebe4d411

**Comment by aulneau** [comment]
Nice this looks great. Thanks for posting @friedger

**Comment by zone117x** [comment]
This would be nice. Few thoughts:
* Bundling the wasm for the blockstack.js dist file may pose a challenge. 
  * AFAIK this requires embedding a b64 string of the wasm binary file. Which for secp256k1.wasm alone is 231KB (120KB compressed). 
  * We'd need to add some browserify plugins (or use webpack). And we probably want to wait until the lib is refactored in smaller components as suggested by @yknl. 
  * Are we willing to drop support for browsers that don't support webassembly? If not, we'd need to make sure to support a fallback (more bloat). 
* This may help with encrypted file upload memory bloat problems https://github.com/blockstack/blockstack.js/issues/564#issuecomment-447128821 since I suspect this rust/webassembly implementation is not creating lots of internal js buffer/array copies.

**Comment by expenses** [comment]
[Wasm support](https://caniuse.com/#search=wasm) is great enough that we're really only missing out on IE and Opera Mini users. IE is probably not worth worrying about, but not supporting Opera Mini might ignore a lot of users in Africa.

**Comment by zone117x** [comment]
Hmm, I'm not really sure what caniuse.com is indicating with Opera Mini. It shows info for a version released in 2015, despite more modern versions being released. 

If Opera Mini 2015 is heavily used in Africa then I think there are already several web APIs used in blockstack.js that are not supported -- notably [`crypto.getRandomValues`](https://caniuse.com/#feat=getrandomvalues) and [`CORs`](https://caniuse.com/#feat=cors)
