### ISSUE TITLE
For some reason redirectToSignIn method scrolls the website to the bottom as a side-effect

### ISSUE THREAD

**Issue by tautvilas** [stx-labs/stacks.js#639]
You can try this on https://decentus.com/ . Try pressing 'Log in' while being logged out - the page is scrolled to the button and protocol handler dialog is displayed on top. Tested on chrome and firefox

**Comment by zone117x** [comment]
This is probably happening due to some hidden elements being inserted onto the page for protocol handler detection purposes. I think we just need to use some additional style properties that hide the element(s) better with no side effect like page scrolling. 

Here is the suspect styling code:
https://github.com/blockstack/blockstack.js/blob/6a8fafb13dd6d272065d030308bebeb29b207bb1/src/auth/authApp.ts#L218

Note that we cannot use `style.display = 'none'` here otherwise the `focus` events will not work. 

Maybe some floating or absolute positioning? 

@aulneau any suggestions?

**Comment by aulneau** [comment]
hmm yeah I bet the browser is scrolling to the newly focused input that is at the bottom of the page. We could try this:

```jsx
 inputStyle.position = 'absolute'
 inputStyle.top = '0'
```
