### ISSUE TITLE
`transitKey` is undefined on Safari after authentication with `handlePendingSignIn`

### ISSUE THREAD

**Issue by KNTH01** [stx-labs/stacks.js#686]
Hi,

`transitKey` is undefined on Safari after authentication with `handlePendingSignIn`.
It works perfectly on Chrome.

Here is a screenshot of what happens:

![image](https://user-images.githubusercontent.com/1632391/62530135-45348b80-b840-11e9-95dc-a4d25afa3712.png)

As you can see, an exception has been thrown: `Unhandled Promise Rejection: LoginFailedError: Failed to login: Authenticating with protocol > 1.1.0 requires transit key, and none found.` => https://github.com/blockstack/blockstack.js/blob/master/src/auth/authApp.ts#L333

I looked in the source code, and is fetch from the `userSession`, so I debugged with:
```
console.log(
  'userSession.store.getSessionData().transitKey :',
  userSession.store.getSessionData().transitKey
)
```

You can see that on Chrome, the transitKey is set while on Safari it's `undefined`.

Hosted example can be checked here: https://gekri.com

Thanks for help,

**Comment by yknl** [comment]
Did authentication start on Safari? Was there any step in during the auth flow where a different browser was involved?

**Comment by KNTH01** [comment]
> Did authentication start on Safari? Was there any step in during the auth flow where a different browser was involved?

Nope, it's all start with Safari browser:
- I access to https://gekri.com using Safari.
- Click on SignIn
- Being redirected to `browser.blockstack.org` to proceed to the authentication
- Redirected back to https://gekri.com/?authResponse=eyJ[.....]
- Then `transitKey` is `undefined` while it works fine on Chrome.

I just take a look to the NoteRiot app because its authentication works on Safari.

It works because it uses the deprecated version of the `handlePendingSignIn` method:
- https://gitlab.com/riot.ai/NoteRiot/blob/master/src/main.js#L38
- https://gitlab.com/riot.ai/NoteRiot/blob/master/src/App.vue#L147

What are your thoughts?

**Comment by KNTH01** [comment]
This is how I configured Blockstack.js:

```javascript
// ~/libs/user-session.js
import { UserSession, AppConfig } from 'blockstack'

export const appConfig = new AppConfig(['store_write'])
export const userSession = new UserSession({ appConfig })

window.userSession = userSession
```

Then I succeed to have a dirty fix:

```
- import { userSession } from '~/libs/user-session'
+ const userSession = window.userSession

userSession.handlePendingSignIn() // from the window.userSession
```

I now use the `window.userSession` instead of using its reference.

I do not understand why this is happening...

**Comment by yknl** [comment]
When I tested https://gekri.com  yesterday with Safari, I was able to log in fine. Are you by any chance using a private safari window?

**Comment by KNTH01** [comment]
> When I tested https://gekri.com yesterday with Safari, I was able to log in fine. Are you by any chance using a private safari window?

I published this fix https://github.com/blockstack/blockstack.js/issues/686#issuecomment-519065030 so it's work now.

I still don't understand why I have to use the reference handled by the global object `window` instead of importing it...

**Comment by zone117x** [comment]
Seems like an app bundling problem related to es6 module transforms. How are you packing and publishing your app?

**Comment by KNTH01** [comment]
Using https://nuxtjs.org with Webpack under the hood.

**Comment by zone117x** [comment]
The code sample in https://github.com/blockstack/blockstack.js/issues/686#issuecomment-519065030 is showing one of your source files `~/libs/user-session.js` performing imports & exports, and another one of your source files running into problems referencing exports from your `~/libs/user-session.js` file. 
This implies the problem is with how you are structuring modules within your src, possibly in conjunction with how your nuxtjs (or webpack or babel) config is performing module transforms. 

For example, you are performing an es6 export of a `userSession` variable in one line:
`export const userSession = new UserSession({ appConfig })`
Then right below it you are creating a globally scoped variable of the same name by assigning it to `window.userSession`:
`window.userSession = userSession`. 

It's not clear what that code will be transformed into during the build process.  Can you create an isolated example repo that reproduces the problem? Otherwise, I'm not sure how we can help, or if this issue is even related to blockstack.js.

**Comment by stackatron** [comment]
@KevinNTH were you able to solve this? Closing for now. Happy to reopen if you still need help.

**Comment by KNTH01** [comment]
Yeah, I didn't try again since I deployed my [work around](https://github.com/blockstack/blockstack.js/issues/686#issuecomment-519065030).

I was expecting to not use `window` global to store `userSession`.
