### ISSUE TITLE
Explore ways to retry a register

### ISSUE THREAD

**Issue by muneeb-ali** [stx-labs/stacks.js#73]
@JFiscella ended up in a situation where a preorder went through but register didn't for some reason and the CLI was not retrying a register automatically (which should not happen). This should work in the current code, but it didn't in this particular case so need to explore it more. The behavior is not deterministic. A register operation that @JFiscella tried later on worked.

**Comment by jcnelson** [comment]
If the RPC daemon dies, there's not much recourse, since it's the only mechanism watching for tx confirmations.  However, the RPC daemon in `develop` should pick up where it left off if it gets restarted, and will always ask to unlock and load the wallet before initializing so it can send subsequent transactions.

**Comment by jcnelson** [comment]
This is now fixed.  The RPC daemon can die and be restarted, and it will re-try any pending transactions.
