### ISSUE TITLE
Export HubInfo and makeV1GaiaAuthToken

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#768]
Export `HubInfo` and `makeV1GaiaAuthToken`

**Comment by hstove** [comment]
- Re: `HubInfo` - some parts of the code use `any`, instead of a (not now existant) `HubInfo` interface. [example](https://github.com/blockstack/blockstack.js/blob/master/src/storage/hub.ts#L156). It would be a small improvement to have better types here, and to export this type, so the authenticator can use it.
- Re: `makeGaiaV1AuthToken` - right now, that function makes another request to `/hub_info` of the Gaia hub. Right now, I'm optimizing some code in the authenticator to request this path as little as possible. It would be nice if:
  - this function was exported, so I could use it
  - this function accepted an optional `HubConfig` argument, so that I can pass my existing hub config instead of doing an HTTP request

**Comment by hstove** [comment]
See [this code in keychain](https://github.com/blockstack/blockstack-keychain/commit/3a0635367c2172e5edb3aa9e015ec22f8641e49b#diff-51a388e8d6da6a9ecf075f0f8ad95935) that added a `HubInfo` interface, and defined its own function to make a Gaia auth token
