### ISSUE TITLE
RPC endpoint

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#77]
In the `develop` branches of blockstack-server and blockstack-client, I've been migrating our RPC implementation off of Twisted's JSON/netstring protocol over to something more conventional, with less dependencies.  The code currently uses Python's `SimpleXMLRPCServer` implementation, and expose all server methods to the client via an HTTP(S) interface.  However, we often pass Python dictionaries over the RPC interface, which don't serialize well in XMLRPC (in particular, dictionaries with integer keys).  So what I've ended up doing is adding a custom serializer that translates each RPC into a JSON string and back--effectively implementing JSONRPC over XMLRPC.

This might sound extremely kludgy on first glance, but consider:
- Blockstack-server's RPC paths are disk-bound, since each RPC makes a query against a SQLite file.  The overhead of extra serialization and deserialization is negligible by comparison.
- There is no JSON equivalent to `SimpleXMLRPCServer` in the Python standard library.  Anything we do to remove the XML would either introduce a dependency, or require us to build and ship our own `SimpleJSONRPCServer` implementation.
- Serializing the RPC into a JSON dict and back--fits into less than 50 lines of easy-to-understand Python.  That's considerably smaller than even a modest JSONRPC HTTP server and client, and the bulk of the complex code is already maintained by the Python developers.

The only downside I see to this approach is that this adds a bad design smell, because it uses two serialization formats where only one is strictly necessary.  If there was a `SimpleJSONRPCServer` and `jsonrpclib.ServerProxy` equivalent for JSON that didn't add an external dependency, I'd spring for that in a heartbeat.

**Comment by jcnelson** [comment]
I already know about `jsonrpclib`.  It hasn't been touched in months (maybe because it's so stable now?), but it's over 10x the complexity and adds features we really don't need.

**Comment by muneeb-ali** [comment]
I think this has more to do with Python going for XMLRPC instead of supporting JSON serialization in the standard libraries. So it might look a bit ugly, but is better than having external dependencies. We had to use a [txJSON-RPC](https://github.com/oubiwann/txjsonrpc) earlier which was an external dependency and sometimes lead to installation issues e.g., with Python 3.

I think sticking with SimpleXMLRPCServer works (we're already doing this in [rpc_daemon](https://github.com/blockstack/blockstack-registrar/blob/master/registrar/rpc_daemon.py)) and can try to make it a standard across all packages in blockstack.

**Comment by jcnelson** [comment]
This is now working in the `develop` branch.  No more Twisted.
