### ISSUE TITLE
@blockstack/connect has React dependencies

### ISSUE THREAD

**Issue by giraffekey** [stx-labs/stacks.js#787]
@blockstack/connect has the "react" and "react-dom" dependencies. This means that I have to include React in my dependencies specifically for this even when generating a Vue project. It's a bit annoying to have to install two front-end frameworks for practically no reason so a workaround would be nice.

**Comment by PeterKnight** [comment]
I have also been experimenting with the @blockstack/connect package and got the impression from the docs that react is automatically added as a dependency, but you can't simply install the connect library and expect it to work, as you still get the react is missing errors. 

Also find it a shame that the testapp is coded with a combination of truescript and react. Not every developer is using those tools. 

I tried loading the connect package from unpkg (since that avoids having to add react etc to a project) but that makes using a custom store for the usersession data inside a project convoluted (unless I'm missing something).

Most of my projects use Vue and the react deps is definitely an unwanted complication to add to the mix. Is a better solution for non-React projects possible?

[edit] I now see stencil has been suggested, this would be great
https://github.com/blockstack/ux/issues/320

**Comment by PeterKnight** [comment]
I've done some more experimenting with integrating this in a Vue project. I now have the sign in as an async component and I use the unpkg option so I don't have to pull in React as a project dependency. Something I missed earlier was that you can supply a UserSession instance to showBlockstackConnect.

**Comment by friedger** [comment]
This is now resolved with "@stacks/connect-react" and using stencil in @stacks/auth
