### ISSUE TITLE
Refactor auth to be compatible with new authenticator and connect

### ISSUE THREAD

**Issue by yknl** [stx-labs/stacks.js#798]

**Comment by markmhendrickson** [comment]
One thing I'd suggest addressing during this refactor is how [the blockstack.js reference](https://blockstack.github.io/blockstack.js/) still refers to methods on the library object itself that have actually been moved to the `userSession` object in a previous release (e.g. `blockstack.isUserSignedIn()` should be `blockstack.userSession.isUserSignedIn()`).

This is something I spotted when upgrading my own app to Blockstack Connect, though it would affect developers implementing just blockstack.js for whatever reason.

More generally, the reference should probably be updated to remove guidance on sending users through the authentication flow without Blockstack Connect (e.g. removing `blockstack.redirectToSignIn()` support), assuming we don't want to support authentication integration without Connect going forward.

If we _do_ want to support that type of integration for whatever reason, then we'll want to upgrade blockstack.js to use the new Blockstack App authenticator instead of the deprecated Blockstack Browser.

## Screenshot

<img width="761" alt="Screen Shot 2020-07-08 at 10 39 47" src="https://user-images.githubusercontent.com/28991/86897504-c870f800-c107-11ea-89d3-070fc62641f3.png">

**Comment by yknl** [comment]
Good catch @markmhx, we will need to update this documentation as part of the refactor.
