### ISSUE TITLE
Break private key into Shamir secrets

### ISSUE THREAD

**Issue by jcnelson** [stx-labs/stacks.js#86]
We'll eventually support multisig name ownership, but before we do so, I'd like to add support for breaking the master private key into Shamir secrets, which can be distributed across multiple (air-gapped) devices.  I'd make it easy to do automatically, with clear instructions on what to do and how to re-combine them.  I think this would get us a good chunk of the benefits of multisig, without having to make any potentially-consensus-breaking changes.

**Comment by shea256** [comment]
Oh I thought we already supported multi-sig. Is that not the case?

If the name is owned by an arbitrary scriptPubKey then all ownership types, including multi-sig, would be supported.

**Comment by jcnelson** [comment]
> Oh I thought we already supported multi-sig. Is that not the case?

The tooling doesn't support it--i.e. the CLI doesn't set up multisig, and neither the CLI nor the server generate multisig scripts.  I also can't say for sure that the server will accept multisig addresses, since we haven't tried it yet (still need to move `blockstack-integration-tests` over to using `-regtest`).

**Comment by shea256** [comment]
OK can we set aside some time to try? I have a hunch that it will work. As long as the consensus hashes are calculated from the scriptPubKey's (and not public keys) then it shouldn't be consensus breaking. Would you say that is a valid assumption?

**Comment by jcnelson** [comment]
I have the same hunch, but I just want to be sure.  Tracking the details here:  https://github.com/blockstack/blockstack-integration-tests/issues/1

**Comment by shea256** [comment]
Also, I agree that integrating Shamir's Secret Sharing could be a good first step, since we already have our own library for it and it should be relatively simple to plug in.

In addition, we should set up a time schedule on our roadmap for supporting multi-sig.

In my view, multi-sig is much more useful than Shamir's Secret Sharing (think about multiple devices and the security implications of communicating shares to one device) and is among the top priorities for new updates to the Blockstack core.

This will let us do multi-sig not only in the CLI but also in the desktop app, which will be an important feature to add in one of the earlier releases.

**Comment by shea256** [comment]
@jcnelson ok cool, I'll watch that thread as well.

**Comment by jcnelson** [comment]
We're just going to do straight-up multisig.
