### ISSUE TITLE
CLI: Support for optional parameters in contract calls

### ISSUE THREAD

**Issue by agraebe** [stx-labs/stacks.js#900]
When the CLI is used to make a contract call that has optional values, it errors out:

```
stx call_contract_func ST000000000000000000002AMW42H pox delegate-stx 0 0 <key> -t
Error: Contract function contains unsupported Clarity ABI type: (optional unit)
```

This seems because we don't have support for the Clarity value for optional types.

cc @yknl

**Comment by yknl** [comment]
Looks like we need to update the Clarity ABI checking code in `@stacks/transactions` to support optional uint cc @reedrosenbluth

**Comment by reedrosenbluth** [comment]
Hmm. The ABI checking should definitely support `(optional uint`)... I just tested it out and it seems to be working. Here's a test demonstrating this: https://github.com/blockstack/stacks.js/commit/a3daf0bb94d8668ca716be5980a06c1cc5443d91

**Comment by reedrosenbluth** [comment]
@agraebe can you provide any more details as to what is going on here?

**Comment by reedrosenbluth** [comment]
@yknl did some digging and it looks like this error is actually coming from the CLI: https://github.com/blockstack/stacks.js/blob/1f2b5fd8bdf1c2b5866e8171163594d7708a8c7a/packages/cli/src/utils.ts#L838

However, the same bug is present in the transactions package here: https://github.com/blockstack/stacks.js/blob/1f2b5fd8bdf1c2b5866e8171163594d7708a8c7a/packages/transactions/src/contract-abi.ts#L435

I believe these were left unimplemented because parsing recursive data types is more challenging

**Comment by iamgenchi** [comment]
Hi Blockstack Team, this is indeed not working from the CLI, do you have an alternative to make a contract call that has optional values?

**Comment by agraebe** [comment]
I would try the following:
- [Explorer Sandbox](https://explorer.stacks.co/sandbox?chain=mainnet)
- [Stacks Blockchain API client with Clarity Values](https://blockstack.github.io/stacks-blockchain-api/client/classes/smartcontractsapi.html#callreadonlyfunction)

**Comment by agraebe** [comment]
closing in favor of: https://github.com/blockstack/stacks.js/issues/1100
