### ISSUE TITLE
[CLI] register crashes with unknown method error

### ISSUE THREAD

**Issue by MarvinJanssen** [stx-labs/stacks.js#922]
**Describe the bug**
Blockstack CLI `register` command fails with an unknown method error.

**What version of Blockstack.js are you using?**
```
"@stacks/cli": "^1.0.1"
```

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Blockstack CLI

**To Reproduce**
```
./bin.js register example.namespace "$PK" "$PK" https://hub.blockstack.org
```

**Expected behavior**
Successful name registration.

**Console log**
```
{"error":{},"level":"error","message":"uncaughtException: method is not a function\nTypeError: method is not a function\n    at CLIMain (/stacks/node_modules/@stacks/cli/src/cli.ts:1881:5)\n    at Object.<anonymous> (/stacks/node_modules/@stacks/cli/src/index.ts:32:1)\n    at Module._compile (node:internal/modules/cjs/loader:1102:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)\n    at Module.load (node:internal/modules/cjs/loader:967:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:807:14)\n    at Module.require (node:internal/modules/cjs/loader:991:19)\n    at require (node:internal/modules/cjs/helpers:92:18)\n    at Object.<anonymous> (/stacks/node_modules/@stacks/cli/dist/index.js:7:20)\n    at Module._compile (node:internal/modules/cjs/loader:1102:14)","stack":"TypeError: method is not a function\n    at CLIMain (/stacks/node_modules/@stacks/cli/src/cli.ts:1881:5)\n    at Object.<anonymous> (/stacks/node_modules/@stacks/cli/src/index.ts:32:1)\n    at Module._compile (node:internal/modules/cjs/loader:1102:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)\n    at Module.load (node:internal/modules/cjs/loader:967:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:807:14)\n    at Module.require (node:internal/modules/cjs/loader:991:19)\n    at require (node:internal/modules/cjs/helpers:92:18)\n    at Object.<anonymous> (/stacks/node_modules/@stacks/cli/dist/index.js:7:20)\n    at Module._compile (node:internal/modules/cjs/loader:1102:14)","exception":true,"date":"Thu Jan 21 2021 21:47:54 GMT-0800 (Pacific Standard Time)","process":{"pid":12258,"uid":501,"gid":20,"cwd":"/stacks/node_modules/@stacks/cli","execPath":"/.nvm/versions/node/v15.3.0/bin/node","version":"v15.3.0","argv":["/.nvm/versions/node/v15.3.0/bin/node","/stacks/node_modules/@stacks/cli/bin.js","register","example.namespace","<PK>","<PK>","https://hub.blockstack.org"],"memoryUsage":{"rss":128794624,"heapTotal":79298560,"heapUsed":56122008,"external":2265376,"arrayBuffers":1266855}},"os":{"loadavg":[1.48583984375,1.3935546875,1.6376953125],"uptime":112821},"trace":[{"column":5,"file":"/stacks/node_modules/@stacks/cli/src/cli.ts","function":"CLIMain","line":1881,"method":null,"native":false},{"column":1,"file":"/stacks/node_modules/@stacks/cli/src/index.ts","function":null,"line":32,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1102,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1131,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":967,"method":"load","native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":807,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":991,"method":"require","native":false},{"column":18,"file":"node:internal/modules/cjs/helpers","function":"require","line":92,"method":null,"native":false},{"column":20,"file":"/stacks/node_modules/@stacks/cli/dist/index.js","function":null,"line":7,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1102,"method":"_compile","native":false}]}
```

**Desktop (please complete the following information):**
 - OS: macOS 11.1

**Comment by thevinchi** [comment]
I'm seeing this today, even with a simple `stx names ID-foo` using a fresh install.

Version: @stacks/cli@1.4.1

**Environment:**
* OS: ubuntu:20.04 container
* Node: v14.16.1
* NPM: 7.11.1

**Comment by ahsan-javaid** [comment]
As @MarvinJanssen mentioned cli `register` command crashes with unknown method error. I looked into the `cli` package and figured out that there are around `25` commands that were intentionally removed from the cli package. Below is the commit reference: https://github.com/blockstack/stacks.js/commit/67812306cfa5c9920f058d18bde2c44d66bf831d

As per this commit it is very clear that `register` and lot of other commands are removed. I am not sure what was the reason to remove these commands. 
That's why `unknown method error` is expected to come on these removed commands including `register` command mentioned by Marvin. 

Secondly due to this issue the cli documentations at https://docs.stacks.co/references/stacks-cli does not align with the implementation. As per documentation these commands are expected to work including `register` command. May be documentation is not up to date as if we removed these commands from `cli `then we should also update the documentation to make it compatible with `cli` implementation. 

Questions:
1.  Should we bring back these commands implementation in cli or not.. is it intentional .. need thought's
2. Or do we only need to fix `register` command as mentioned in this issue
3. What about documentation https://docs.stacks.co/references/stacks-cli as it does not align with the cli commands. As `register` and other commands are expected to work per docs but these commands are removed from cli implementation.

cc: @agraebe @zone117x

**Comment by agraebe** [comment]
the CLI isn't well maintained nor documented. and a lot of commands and docs are from pre-Stacks 2.0 times. `register` is likely required for BNS functionality and I don't think the Stacks 2.0 BNS implementation was ever used inside the CLI

Given that this issue is long standing, I'd say we put it in the icebox until we have a better sense of resourcing and direction for the CLI package
