### ISSUE TITLE
CLI's package.json missing script to auto-install dependencies after CLI installation 

### ISSUE THREAD

**Issue by rlin415** [stx-labs/stacks.js#964]
**Describe the bug**
After running `npm install -g @stacks/cli`, I tried using the `stx` command which failed with this error message:
```
internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'typescript
```
I had to manually run `npm i` inside the CLI package to resolve the error.
**What version of Blockstack.js are you using?**
v1.2.4
**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Blockstack CLI
**To Reproduce**
1. Run `npm install -g @stacks/cli`
2. Run `stx`

**Expected behavior**
`stx` runs with no issues after installing stacks CLI.

**Console log**
```
internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'typescript
```
**Desktop (please complete the following information):**
 - OS: MacOS Big Sur v11.1

**Comment by marcosc90** [comment]
There are ~two~ one possible solution:

1. add `typescript` to `@stacks/cli` dependencies:
> You'll need to install typescript locally since v8, it's using require.resolve which has its own separate limitations but is used to resolve a different issue. That means typescript is resolved from where you're running it right now.

See: https://github.com/TypeStrong/ts-node/issues/707#issuecomment-457448149

2. ~bump `ts-node` to `9.y.z`~

~This is most likely the way to go, but I have to check that everything still works after a major version bump.~



_I'm working on this_

**Comment by marcosc90** [comment]
`ts-node` has `typescript` as a `peerDependency`, and peer dependencies are not installed by default from NPM v3-v6. NPM 7 reintroduced the [automatic installation of peer dependencies](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/).

The issue is no longer present on the latest NPM version. To fix it for those using older versions of NPM, listing `typescript` as a dependency is the only solution.
