### ISSUE TITLE
Node unable to install @stacks/cli, neither locally or when using gitpod.

### ISSUE THREAD

**Issue by chancelorb** [stx-labs/stacks.js#971]
**Describe the bug**
I am unable to install @stacks/cli

**Is the bug present in the Blockstack CLI, Gaia hub, Connect or Blockstack Browser?**
Blockstack CLI

**To Reproduce**
1.  Run ```npm i --global @stacks/cli```

**Expected behavior**
I expect @stacks/cli to install.

**Screenshots**
![Screen Shot 2021-03-11 at 11 59 42 AM](https://user-images.githubusercontent.com/32469034/110848533-10ca5200-8263-11eb-9180-b189b8ad8a4f.png)

**Desktop (please complete the following information):**
 - A NodeJS playground for Clarity onboarding using Gitpod, for the Clarity "Hello World" tutorial.
 - macOS Big Sur v11.0.1
 - macOS Catalina 10.15.7

**Comment by reedrosenbluth** [comment]
What version of node are you using locally? It works fine for me on `v15.11.0` with npm `7.6.0`

**Comment by chancelorb** [comment]
I am locally using versions ```v15.11.0``` with npm ```7.6.0```.
If you use the link in the Hello World tutorial to gitpod it gives the same error with version ```v14.16.0``` with npm ```7.5.6```

**Comment by chancelorb** [comment]
stacks/cli now working locally but not on gitpod. I did not change any of my Node or npm versions.

**Comment by matronator** [comment]
Have the same issue, can't install it on Node v14, outputs this message:

```d
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path /Users/matejbystricky/.nvm/versions/node/v14.16.1/lib/node_modules/@stacks/cli/node_modules/@stacks/blockchain-api-client
npm ERR! command failed
npm ERR! command sh -c npx shx find lib/index.js || npm run build
npm ERR! > @stacks/blockchain-api-client@0.34.2 build
npm ERR! > rimraf ./lib && npm run generate-openapi && npm run build:node && npm run build:browser
npm ERR! sh: shx: command not found
npm ERR! sh: rimraf: command not found

npm ERR! A complete log of this run can be found in:
...
```

Full log: [2021-07-24T02_27_21_747Z-debug.log](https://github.com/blockstack/stacks.js/files/6871794/2021-07-24T02_27_21_747Z-debug.log)

**Comment by ahsan-javaid** [comment]
I did some investigation on this issue and below are my findings that may help in cli installation:

`Node version: v14.17.3` and `16.5.0`
###  Installing @stacks/cli locally
- `mkdir cli-test`
- `cd cli-test`
- `npm init`
- `npm i @stacks/cli --save`

These commands successfully installed @stacks/cli locally

###  Installing @stacks/cli globally
- `sudo npm i @stacks/cli -g` // This command fails due to write permission issues
- Use the troubleshoot section in this [link](https://docs.stacks.co/references/stacks-cli) to allow the write permissions
### Workaround to bypass the permission errors
Use below command to install cli globally by bypassing permission errors
`sudo npm i @stacks/cli -g --unsafe-perm=true --allow-root`

### Install @stacks/cli using gitpod
- Followed [gitpod quick start guide](https://www.gitpod.io/docs/quickstart/typescript) to launch the gitpod container
- In the gitpod terminal on browser executed `npm i @stacks/cli -g` 
- cli installed without any errors
- node version inside gitpod terminal was `v14.17.3`
- Terminal snapshot is here: 
<img width="1264" alt="Screenshot 2021-07-27 at 7 44 24 PM" src="https://user-images.githubusercontent.com/23546098/127175044-d22f9c4d-3a06-40fe-af46-6b240bc15b65.png">

### Test @stacks/cli installation with github workflow
- Created a sample project with @stacks/cli dependency
- Add a github workflow to execute npm install and test `stx  help command`
- Pushed code on gihub to see if CI job passes or not
- The workflow output was successful

**Comment by matronator** [comment]
For me it didn't fail due to permission issues, but because of `shx` and `rimraf` commands were not found. Excerpt from the debug log in my [previous comment](https://github.com/blockstack/stacks.js/issues/971#issuecomment-885989310):

<samp><kbd>1720 info run @stacks/blockchain-api-client@0.34.2 postinstall node_modules/@stacks/cli/node_modules/@stacks/blockchain-api-client npx shx find lib/index.js || npm run build
1721 info run @stacks/blockchain-api-client@0.34.2 postinstall { code: 127, signal: null }
1722 timing reify:rollback:createSparse Completed in 1531ms
1723 timing reify:rollback:retireShallow Completed in 0ms
1724 timing command:install Completed in 31422ms
1725 verbose stack Error: command failed
1725 verbose stack     at ChildProcess.<anonymous> (/Users/matejbystricky/.nvm/versions/node/v14.16.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1725 verbose stack     at ChildProcess.emit (events.js:315:20)
1725 verbose stack     at maybeClose (internal/child_process.js:1048:16)
1725 verbose stack     at Socket.<anonymous> (internal/child_process.js:439:11)
1725 verbose stack     at Socket.emit (events.js:315:20)
1725 verbose stack     at Pipe.<anonymous> (net.js:673:12)
1726 verbose pkgid @stacks/blockchain-api-client@0.34.2
1727 verbose cwd /Users/matejbystricky/Documents
1728 verbose Darwin 20.3.0
1729 verbose argv "/Users/matejbystricky/.nvm/versions/node/v14.16.1/bin/node" "/Users/matejbystricky/.nvm/versions/node/v14.16.1/bin/npm" "install" "-g" "@stacks/cli"
1730 verbose node v14.16.1
1731 verbose npm  v7.20.1
1732 error code 127
1733 error path /Users/matejbystricky/.nvm/versions/node/v14.16.1/lib/node_modules/@stacks/cli/node_modules/@stacks/blockchain-api-client
<b>1734 error command failed
1735 error command sh -c npx shx find lib/index.js || npm run build
1736 error > @stacks/blockchain-api-client@0.34.2 build
1736 error > rimraf ./lib && npm run generate-openapi && npm run build:node && npm run build:browser
1737 error sh: shx: command not found
1737 error sh: rimraf: command not found</b>
1738 verbose exit 127
</kbd></samp>

**Comment by zone117x** [comment]
Looks like [`npx`](https://docs.npmjs.com/cli/v7/commands/npx/) isn't functioning correctly on your system. Try running `npx shx echo hello`, you should see it download/cache/run an the `shx` npm package, like so:
```
$ npx shx echo hello
npx: installed 21 in 3.35s
hello
```

**Comment by michaelhall923** [comment]
I had the same problem, it was fixed with the following commands.
```
npm i shx -g
npm i rimraf -g
```
After that run
```
npm install --global @stacks/cli
```

**Comment by matronator** [comment]
@zone117x Nope:

```bash
sh: shx: command not found
```

@michaelhall923 That workaround solves it, but there should be a better way without having to install two 3rd-party packages **_globally_**. Uninstalling them right after is okay I guess, but still. Thanks though :)
